<%
database = ENV['DATABASE_NAME'].presence || 'ittern'
user = ENV['DATABASE_USER'].presence || ENV['USER']
password = ENV['DATABASE_PASSWORD']
host = ENV['DATABASE_HOST'].presence || 'localhost'
port = ENV['DATABASE_PORT'].presence || 5432
%>

default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'].presence || "postgres://#{user}:#{password}@#{host}:#{port}/#{database}" %>
  pool: 10

development:
  <<: *default

test: &test
  <<: *default
  url: <%= ENV['DATABASE_TEST_URL'] %>

production:
  <<: *default
  # この辺はdeployを考えるときにちゃんとする
